### ISSUE TITLE
Cannot upload a folder

### ISSUE THREAD

**Issue by shengwubin** [ashishdoneriya/phpFileManager#14]
Hi,

I am working on a project that needs file management using web pages, and this project is definitely what I expect. However, I find that I cannot upload a folder. For example, if I click "Add Folder" button, the file selection UI shows up.
![image](https://user-images.githubusercontent.com/18481600/109375905-5e16ee80-7875-11eb-9cb3-82ee68969bb7.png)
![image](https://user-images.githubusercontent.com/18481600/109375947-bf3ec200-7875-11eb-8883-86521780f6df.png)

After selecting my folder, a message box shows up:
![image](https://user-images.githubusercontent.com/18481600/109375960-e8f7e900-7875-11eb-9837-b645938eb40c.png)

The problem is that after clicking the blue button "upload", nothing happens so that I actually return to the initial upload UI.
![image](https://user-images.githubusercontent.com/18481600/109375905-5e16ee80-7875-11eb-9cb3-82ee68969bb7.png)

No HTTP request is made, so I fail to upload a folder. I wonder if it is a problem that only happens on my machine?
![image](https://user-images.githubusercontent.com/18481600/109375996-3aa07380-7876-11eb-95b4-51c4eb2bec00.png)

**Comment by ashishdoneriya** [comment]
@shengwubin I have fixed the bug. Kindly download the latest release

**Comment by shengwubin** [comment]
> @shengwubin I have fixed the bug. Kindly download the latest release

Thanks!
